title: CYBREMONDAY
author: CYBREMONDAY Staff
description: A weekly cybrezine
lang: en
permalink: /:slug/
timezone: US/Pacific
markdown: kramdown
collections:  #  Order matters!  Liquid in collections is parsed sequentially.

  #  Freeform content
  CPLB:  #  CYBREMONDAY alternate playlists; freeform
    output: true
  CMBD:  #  CYBREMONDAY embedded content; freeform
    output: true
  CGST:  #  CYBREMONDAY guest issues; freeform
    output: true

  #  Numbered content
  CHEX:  #  CYBREMONDAY hex colours; tracks CMON
    output: false
  CPLA:  #  CYBREMONDAY issue playlists; tracks CMON
    output: true
  CPRJ:  #  CYBREMONDAY featured projects; tracks CMON
    output: true
  CMON:  #  CYBREMONDAY original numbered issues; VVNN (V = Volume; N = Issue №)
    output: true
  CNTR:  #  CYBREMONDAY interludes; tracks *previous* CMON
    output: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
include:  #  Not handled by default by jekyll-optional-front-matter
  - CONTRIBUTING.md
  - README.md
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
sass:
    style: compressed
plugins:
  - jekyll-coffeescript
  - jekyll-redirect-from
  - jekyll-optional-front-matter
defaults:
  -
    scope:
      path: ""
    values:
      author: CYBREMONDAY Staff
      layout: simple
  -
    scope:
      path: bkg
    values:
      type: background
  -
    scope:
      path: cvr
    values:
      type: cover
  -
    scope:
      path: img
    values:
      type: image
  -
    scope:
      path: ntr
    values:
      type: interlude
  -
    scope:
      path: ""
      type: CGST
    values:
      permalink: "/:collection:name/"
  -
    scope:
      path: ""
      type: CMBD
    values:
      permalink: "/:collection:name/"
  -
    scope:
      path: ""
      type: CMON
    values:
      permalink: "/:collection:name/"
  -
    scope:
      path: ""
      type: CNTR
    values:
      permalink: "/:collection:name/"
  -
    scope:
      path: ""
      type: CPLA
    values:
      permalink: "/:collection:name/"
  -
    scope:
      path: ""
      type: CPLB
    values:
      permalink: "/:collection:name/"
