title: &title
  - c: CYBREMONDAY
    o: hi
    a: rend=highlight
author: cybremonday
publisher: cybremonday
description: &description A casual webzine aimed at elucidating conversations and ideas, questioning existing narratives, and promoting discussion regarding life and culture in (cyber/cybre)space.
license: https://www.gnu.org/licenses/gpl-3.0
url: https://cybremonday.net
logo: /img/siri.png
icon: /img/siri_small.png
lang: en
permalink: /:slug/
timezone: US/Pacific
markdown: kramdown
excerpt_separator: ""
collections:  #  Order matters!  Liquid in collections is parsed sequentially.

  #  Freeform content
  CPLB:  #  CYBREPLAY alternate playlists; freeform
    output: true
    title: &CPLB-title
      - Guest
      -
      - c: CYBREPLAY
        o: hi
        a: rend=highlight
    description:
      - A
      -
      - c: *title
      -
      - guest playlist
      - .
  CMBD:  #  CYBREMBED embedded content; freeform
    output: true
    title: &CMBD-title
      - c: CYBREMBED
        o: hi
        a: rend=highlight
    description: &CMBD-description ""
  CDSP:  #  CYBREDISPATCH
    output: true
    title: &CDSP-title
      - c: CYBREDISPATCH
        o: hi
        a: rend=highlight
    description: &CDSP-description
      - Dispatches from the cybre
      - .
  CGST:  #  CYBREMONDAY guest issues; freeform
    output: true
    title: &CGST-title
      - c: *title
      -
      - Guest Issue
    description: &CGST-description
      - A
      -
      - c: *title
      -
      - guest issue
      - .

  #  Numbered content
  CHEX:  #  CYBREMONDAY hex colours; tracks CMON
    output:
  CPLA:  #  CYBREPLAY playlists; tracks CMON
    output: true
    title: &CPLA-title
      - c: CYBREPLAY
        o: hi
        a: rend=highlight
    description:
      - A
      -
      - c: *title
      -
      - playlist
      - .
  CPRJ:  #  CYBREMONDAY featured projects; tracks CMON
    output:
  CMON:  #  CYBREMONDAY original numbered issues; VVNN (V = Volume; N = Issue №)
    output: true
    title: *title
    description: *description
  CMON-r:  #  CYBREMONDAY regularized issues; tracks CMON
    output: true
    title: &CMON-r-title
      - c: *title
      -
      - (
      - regularized
      - )
    description: *description
  CNTR:  #  CYBREMONDAY interludes; tracks *previous* CMON
    output: true
    title: &CNTR-title
      - c: *title
      -
      - Interlude
    description:
      - A
      -
      - c: *title
      -
      - interlude
      - .

exclude:  #  LICENSE.txt does not give the license for the rendered content
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
sass:
  style: compact
plugins:
  - jekyll-coffeescript
  - jekyll-redirect-from
defaults:
  - scope:
      path: ""
    values:
      author: cybremonday
      layout: simple
      license: https://creativecommons.org/licenses/by-sa/4.0/
      publisher: cybremonday
      excerpt: ""
  - scope:
      path: bkg
    values:
      type: background
  - scope:
      path: cvr
    values:
      type: cover
  - scope:
      path: entry
    values:
      layout: entry
  - scope:
      path: feed
    values:
      layout: feed
  - scope:
      path: img
    values:
      type: image
  - scope:
      path: ndx
    values:
      layout: index
  - scope:
      path: ntr
    values:
      type: interlude
  - scope:
      path: ""
      type: CDSP
    values:
      permalink: /:collection:name/
      seo:
        type: PublicationIssue
      series: *CDSP-title
      description: *CDSP-description
  - scope:
      path: ""
      type: CGST
    values:
      permalink: /:collection:name/
      seo:
        type: PublicationIssue
      series: *CGST-title
      description: *CGST-description
  - scope:
      path: ""
      type: CMBD
    values:
      permalink: /:collection:name/
      schema:
        type: WebPage
      series: *CMBD-title
      description: *CMBD-description
  - scope:
      path: ""
      type: CMON
    values:
      permalink: /:collection:name/
      schema:
        type: PublicationIssue
      series: *title
      description: *description
  -
    scope:
      path: ""
      type: CMON-r
    values:
      variants: none
      permalink: /CMON:name-r/
      schema:
        type: PublicationIssue
      series: *CMON-r-title
      description: *description
      series_id: CMON
      series_ext: r
      title: ""
  -
    scope:
      path: ""
      type: CNTR
    values:
      permalink: /:collection:name/
      schema:
        type: RadioEpisode
      series: *CNTR-title
      description: *CNTR-description
  -
    scope:
      path: ""
      type: CPLA
    values:
      permalink: /:collection:name/
      schema:
        type: MusicPlaylist
      series: *CPLA-title
      description: *CPLA-description
  -
    scope:
      path: ""
      type: CPLB
    values:
      permalink: /:collection:name/
      schema:
        type: MusicPlaylist
      series: *CPLB-title
      description: *CPLB-description
